POST http://localhost:5000/roles
Content-Type: application/json

{
    "name": "Delivery"
}


###
POST http://localhost:5000/user
Content-Type: application/json

{
    "uuid" : "SLR1",
    "name" : "Oliver Sykes Admin",
    "email" : "slr@gmail.com",
    "password" : "slr",
    "phonenumber" : "081234567890",
    "roleId" : "1"
}

###
//get all user
GET http://localhost:5000/user

###
GET http://localhost:5000/me

###
// login user admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "lfr1@gmail.com",
    "password" : "lfr18"
}

###
// login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "adm@gmail.com",
    "password" : "adm"
}

###
//logout user
DELETE http://localhost:5000/logout

###
//ADD Product
POST http://localhost:5000/product
Content-Type: application/json

    {
  "name": "Mie Goreng",
  "price": 15000,
  "producttype": "Food",
  "boothId": 1,
  "userId": 2
}

### Delete Product
DELETE http://localhost:5000/product/bcb79db9-91ac-4747-9faf-48fbb9044c56
Content-Type: application/json


###
POST http://localhost:5000/Booth
Content-Type: application/json

    {
  "name": "Booth A",
  "openingTime": "2024-10-22T09:00:00.000Z",
  "closingTime": "2024-10-22T18:00:00.000Z",
  "userId": 2
}

### Membuat Course Baru
POST http://localhost:5000/courses
Content-Type: application/json

{
  "name": "Object Oriented Programming",
  "classname": "Class LK01",
  "startDate": "2024-11-07T07:20:00",
  "endDate": "2024-12-07T08:50:00",
  "userId": 2
}

