POST http://localhost:5000/roles
Content-Type: application/json

{
    "name": "Seller"
}


###
POST http://localhost:5000/user
Content-Type: application/json

{
    "uuid" : "adm1",
    "name" : "Admin 1",
    "email" : "adm1@gmail.com",
    "password" : "dladmv",
    "phonenumber" : "081234567811",
    "roleId" : "1"
}

###
//get all user
GET http://localhost:5000/user

###
GET http://localhost:5000/me

###
// login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "adm@gmail.com",
    "password" : "adm"
}

###
//logout user
DELETE http://localhost:5000/logout

###
//ADD Product
POST http://localhost:5000/product
Content-Type: application/json

    {
  "name": "Nasi Ayam Paket A",
  "price": 15000,
  "producttype": "Food",
  "boothId": 3,
  "userId": 3
}

### Delete Product
DELETE http://localhost:5000/product/bcb79db9-91ac-4747-9faf-48fbb9044c56
Content-Type: application/json


### Add Booth
POST http://localhost:5000/Booth
Content-Type: application/json

    {
  "name": "Rocky Chicken",
  "openingTime": "2024-10-22T09:00:00.000Z",
  "closingTime": "2024-10-22T18:00:00.000Z",
  "userId": 3
}

### Membuat Course Baru
POST http://localhost:5000/courses
Content-Type: application/json

{
  "name": "Object Oriented Programming",
  "classname": "Class LK01",
  "startDate": "2024-11-07T07:20:00",
  "endDate": "2024-12-07T08:50:00",
  "userId": 5
}

###
GET /booth/:boothId/products

###
GET http://localhost:5000/booth/1/products




