POST http://localhost:5000/roles
Content-Type: application/json

{
    "name": "Delivery"
}


###
POST http://localhost:5000/user
Content-Type: application/json

{
    "uuid" : "2502998701",
    "name" : "Delivery",
    "email" : "dlv@gmail.com",
    "password" : "dlv",
    "phonenumber" : "081234567890",
    "roleId" : "3"
}

###
//get all user
GET http://localhost:5000/user

###
GET http://localhost:5000/me

###
// login user admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "lfr1@gmail.com",
    "password" : "lfr18"
}

###
// login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "lfrdel@gmail.com",
    "password" : "lfr18"
}

###
//logout user
DELETE http://localhost:5000/logout

###
//ADD Product
POST http://localhost:5000/product
Content-Type: application/json

    {
  "name": "Mie Ayam",
  "price": 15000,
  "producttype": "Food",
  "boothId": 1,
  "userId": 4
}
###
POST http://localhost:5000/Booth
Content-Type: application/json

    {
  "name": "Booth A",
  "openingTime": "2024-10-22T09:00:00.000Z",
  "closingTime": "2024-10-22T18:00:00.000Z",
  "userId": 1
}
